### ISSUE TITLE
默认会安装fabric1.14.0，运行在python3.7下会报错

### ISSUE THREAD

**Issue by karrychow** [gangly/fablinker#1]

**Comment by karrychow** [comment]
下面是fablinker -f 报错

taceback (most recent call last):
  File "/usr/local/bin/fablinker", line 5, in <module>
    from fablinker import main
  File "/usr/local/lib/python3.7/site-packages/fablinker/__init__.py", line 4, in <module>
    from fablinker.cli import main
  File "/usr/local/lib/python3.7/site-packages/fablinker/cli.py", line 6, in <module>
    from fablinker.fabshell import FabShell
  File "/usr/local/lib/python3.7/site-packages/fablinker/fabshell.py", line 9, in <module>
    import fabric.api as fab
  File "/usr/local/lib/python3.7/site-packages/fabric/api.py", line 10, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/usr/local/lib/python3.7/site-packages/fabric/context_managers.py", line 535
    def accept(channel, (src_addr, src_port), (dest_addr, dest_port)):
                        ^
SyntaxError: invalid syntax

**Comment by karrychow** [comment]
fab date 报错

Traceback (most recent call last):
  File "/usr/local/bin/fab", line 5, in <module>
    from fabric.main import main
  File "/usr/local/lib/python3.7/site-packages/fabric/main.py", line 13, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType' from 'operator' (/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/operator.py)

**Comment by karrychow** [comment]
安装了 fabric2.5之后fablinker -f 也会报错，fab 正常

Traceback (most recent call last):
  File "/usr/local/bin/fablinker", line 5, in <module>
    from fablinker import main
  File "/usr/local/lib/python3.7/site-packages/fablinker/__init__.py", line 4, in <module>
    from fablinker.cli import main
  File "/usr/local/lib/python3.7/site-packages/fablinker/cli.py", line 6, in <module>
    from fablinker.fabshell import FabShell
  File "/usr/local/lib/python3.7/site-packages/fablinker/fabshell.py", line 9, in <module>
    import fabric.api as fab
ModuleNotFoundError: No module named 'fabric.api'

**Comment by jly888** [comment]
安装Fabric3，可以解决报错问题；pip install Fabric3
